### ISSUE TITLE
.\cli.py --help not working

### ISSUE THREAD

**Issue by AlfonsSchmid** [jedie/inverter-connect#19]
Hi I try to to run i with the raspberry pi. It always produces an error. Please see the output of the terminal. I updated to the newest version, but the result is the same. Do you have any idea?
Thanks and BR 
Alfons

```
pi@raspberrypi:~/inverter-connect $ python3.9 ./cli.py --help

+ /home/pi/inverter-connect/.venv/bin/pip-sync /home/pi/inverter-connect/requirements.dev.txt

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
Collecting arrow==1.2.3 (from -r /tmp/tmprb_8bxwc (line 1))
  Using cached arrow-1.2.3-py3-none-any.whl (66 kB)
Collecting astor==0.8.1 (from -r /tmp/tmprb_8bxwc (line 4))
  Using cached https://www.piwheels.org/simple/astor/astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting autopep8==2.0.2 (from -r /tmp/tmprb_8bxwc (line 7))
  Using cached autopep8-2.0.2-py2.py3-none-any.whl (45 kB)
Collecting binaryornot==0.4.4 (from -r /tmp/tmprb_8bxwc (line 10))
  Using cached https://www.piwheels.org/simple/binaryornot/binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
Collecting black==23.3.0 (from -r /tmp/tmprb_8bxwc (line 13))
  Using cached black-23.3.0-py3-none-any.whl (180 kB)
Collecting bleach==6.0.0 (from -r /tmp/tmprb_8bxwc (line 39))
  Using cached bleach-6.0.0-py3-none-any.whl (162 kB)
Collecting bx-py-utils==80 (from -r /tmp/tmprb_8bxwc (line 42))
  Using cached https://www.piwheels.org/simple/bx-py-utils/bx_py_utils-80-py3-none-any.whl (45 kB)
Collecting cachetools==5.3.0 (from -r /tmp/tmprb_8bxwc (line 45))
  Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting certifi==2022.12.7 (from -r /tmp/tmprb_8bxwc (line 48))
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting cffi==1.15.1 (from -r /tmp/tmprb_8bxwc (line 51))
  Using cached cffi-1.15.1.tar.gz (508 kB)
  Preparing metadata (setup.py) ... done
Collecting chardet==5.1.0 (from -r /tmp/tmprb_8bxwc (line 116))
  Using cached chardet-5.1.0-py3-none-any.whl (199 kB)
Collecting charset-normalizer==3.1.0 (from -r /tmp/tmprb_8bxwc (line 119))
  Using cached charset_normalizer-3.1.0-py3-none-any.whl (46 kB)
Collecting codespell==2.2.4 (from -r /tmp/tmprb_8bxwc (line 195))
  Using cached codespell-2.2.4-py3-none-any.whl (234 kB)
Collecting colorama==0.4.6 (from -r /tmp/tmprb_8bxwc (line 198))
  Using cached https://www.piwheels.org/simple/colorama/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting cookiecutter==2.1.1 (from -r /tmp/tmprb_8bxwc (line 201))
  Using cached cookiecutter-2.1.1-py2.py3-none-any.whl (36 kB)
Collecting coverage==7.2.3 (from -r /tmp/tmprb_8bxwc (line 204))
  Using cached coverage-7.2.3.tar.gz (757 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-j03uhkpl/coverage.egg-info
      writing /tmp/pip-modern-metadata-j03uhkpl/coverage.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-j03uhkpl/coverage.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-modern-metadata-j03uhkpl/coverage.egg-info/entry_points.txt
      writing requirements to /tmp/pip-modern-metadata-j03uhkpl/coverage.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-j03uhkpl/coverage.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-j03uhkpl/coverage.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-j03uhkpl/coverage.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'doc/_build'
      no previously-included directories found matching 'doc/_spell'
      no previously-included directories found matching 'tests/eggsrc/build'
      adding license file 'LICENSE.txt'
      writing manifest file '/tmp/pip-modern-metadata-j03uhkpl/coverage.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-j03uhkpl/coverage-7.2.3.dist-info'
      Traceback (most recent call last):
        File "/home/pi/inverter-connect/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/pi/inverter-connect/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/pi/inverter-connect/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 224, in <module>
        File "<string>", line 214, in main
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 104, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-tnozhfrh/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 989, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
          module = import_module(match.group('module'))
        File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/tmp/pip-build-env-tnozhfrh/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 28, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-tnozhfrh/normal/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ModuleNotFoundError: No module named '_ctypes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "/home/pi/inverter-connect/.venv/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
  File "/home/pi/inverter-connect/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/inverter-connect/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/pi/inverter-connect/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/inverter-connect/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/inverter-connect/.venv/lib/python3.10/site-packages/piptools/scripts/sync.py", line 174, in cli
    sync.sync(
  File "/home/pi/inverter-connect/.venv/lib/python3.10/site-packages/piptools/sync.py", line 244, in sync
    run(  # nosec
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/pi/inverter-connect/.venv/bin/python', '-m', 'pip', 'install', '-r', '/tmp/tmprb_8bxwc', '--extra-index-url', 'https://www.piwheels.org/simple']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/pi/inverter-connect/./cli.py", line 115, in <module>
    main(sys.argv)
  File "/home/pi/inverter-connect/./cli.py", line 101, in main
    verbose_check_call(PIP_SYNC_PATH, str(DEP_LOCK_PATH))
  File "/home/pi/inverter-connect/./cli.py", line 81, in verbose_check_call
    return subprocess.check_call(popen_args)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(PosixPath('/home/pi/inverter-connect/.venv/bin/pip-sync'), '/home/pi/inverter-connect/requirements.dev.txt')' returned non-zero exit status 1.

```

**Comment by jedie** [comment]
Sorry, i have no idea. A little bit strange looks this lines:
![grafik](https://user-images.githubusercontent.com/71315/235588678-5a5c24da-dbae-4082-9f83-d9de7b282826.png)

And there is a Python version mismatch: You start the cli with **python3.9**, but later in the traceback you can see that **python3.10** is used.

Maybe try 3.10, e.g.:
```
pi@raspberrypi:~/inverter-connect $ rm -Rf .venv
pi@raspberrypi:~/inverter-connect $ python3.10 ./cli.py --help
```
What's the output of: `python3 --version` ? On my Pi it's 3.9.2, but i used https://dietpi.com/

**Comment by jedie** [comment]
Hm. Rust toolchain is neede, because [requirements.dev.txt](https://github.com/jedie/inverter-connect/blob/main/requirements.dev.txt) is installed. We have to split the normal use case. So i made #22 for this.

Your output suggest that "cryptography" needs Rust. But on my Pi i haven't Rust installed.

Think the trick is to enable https://www.piwheels.org/
Just create the file `/etc/pip.conf` with the content:
```
[global]
extra-index-url=https://www.piwheels.org/simple
```

Think i should add this to README

**Comment by giovanne123** [comment]
FYI, on my Pi already exists.
![image](https://user-images.githubusercontent.com/16689453/235927080-1eaf7682-b473-449e-82cc-a17553a64906.png)

Btw: in addition I don't want to modify python directly on my OS-level to prevent other stuff stop working ;-)

**Comment by jedie** [comment]
> FYI, on my Pi already exists.

Hm. Sad.
Than i don't know what's the difference between plain Raspian and my dietpi installation :(

> Btw: in addition I don't want to modify python directly on my OS-level to prevent other stuff stop working ;-)

That's why the script creates and used a python virtualenv ;)

**Comment by jedie** [comment]
@AlfonsSchmid @giovanne123 I started to tackle #22 in https://github.com/jedie/inverter-connect/pull/23

You can already tried it on your Pi by switch to the "fix#22" branch, e.g.:
```
~/inverter-connect$ git fetch
~/inverter-connect$ git checkout origin/fix#22
~/inverter-connect$ ./cli.py --help
```

**Comment by AlfonsSchmid** [comment]
@jedie, thanks a lot. I will try and give a feedback. Please give me a little time.

**Comment by giovanne123** [comment]
cli.py - is working for me now
(dev-cli.py - still isn't working, will have a look for it later...)

**Comment by jedie** [comment]
dev-cli.py ist only needed for developers 😉
